files:
  - source: /docs/en/3.2/*.md
    translation: /docs/%two_letters_code%/3.2/%original_file_name%
  - source: /docs/en/3.2/api/*.md
    translation: /docs/%two_letters_code%/3.2/api/%original_file_name%
  - source: /en/*.md
    translation: /%two_letters_code%/%original_file_name%
  - source: /en/api/*.md
    translation: /%two_letters_code%/api/%original_file_name%

